<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="sele_tests.ResTest-20201213222713" tests="1" file="sele_tests.py" time="4.918" timestamp="2020-12-13T22:27:18" failures="0" errors="1" skipped="0">
	<testcase classname="sele_tests.ResTest" name="test_should_issue_res_message" time="4.918" timestamp="2020-12-13T22:27:18">
		<error type="TypeError" message="append() takes exactly one argument (2 given)"><![CDATA[Traceback (most recent call last):
  File "c:\python38-32\lib\unittest\case.py", line 60, in testPartExecutor
    yield
  File "c:\python38-32\lib\unittest\case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "c:\python38-32\lib\unittest\case.py", line 633, in _callTestMethod
    method()
  File "c:\users\hp\desktop\cp\src\unittest\python\sele_tests.py", line 10, in test_should_issue_res_message
    x = Rs(out)
  File "c:\users\hp\desktop\cp\src\main\python\sele.py", line 67, in Rs
    x.append(c.test_url(),c.test_login_correct())
TypeError: append() takes exactly one argument (2 given)
]]></error>
	</testcase>
</testsuite>
